apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: prod
  annotations:
    ingress.bluemix.net/proxy-connect-timeout: "serviceName=frost-http timeout=75s"
    ingress.bluemix.net/proxy-read-timeout: "serviceName=frost-http timeout=3m"
    ingress.bluemix.net/client-max-body-size: "512m"
    ingress.bluemix.net/redirect-to-https: "true"
    ingress.bluemix.net/rewrite-path: |
      serviceName=video-analysis rewrite=/;
      serviceName=social-media-annotation-tool rewrite=/;
      serviceName=frost-server-frost-server-http rewrite=/;
      serviceName=mobileapp rewrite=/browser/www/;
      serviceName=object-store rewrite=/;
  name: rules-prod
spec:
  tls:
  - hosts:
    - beaware-1.eu-de.containers.appdomain.cloud
    secretName: beaware-1
  rules:
  - host: beaware-1.eu-de.containers.appdomain.cloud
    http:
      paths:
        - path: /video-analysis/
          backend:
            serviceName: video-analysis
            servicePort: 7777
        - path: /social-media-annotation-tool/
          backend:
            serviceName: social-media-annotation-tool
            servicePort: 2020
        - path: /sensor-things-server/
          backend:
            serviceName: frost-server-frost-server-http
            servicePort: 8080
        - path: /mobileapp/
          backend:
            serviceName: mobileapp
            servicePort: 8000
        - path: /servlet/is/
          backend:
            serviceName: knowledgebase
            servicePort: 80
        - path: /Bitmaps/
          backend:
            serviceName: knowledgebase
            servicePort: 80
        - path: /css/
          backend:
            serviceName: knowledgebase
            servicePort: 80
        - path: /js/
          backend:
            serviceName: knowledgebase
            servicePort: 80
        - path: /object-store/
          backend:
            serviceName: object-store
            servicePort: 8080
