apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: prod
  annotations:
    ingress.bluemix.net/redirect-to-https: "true"
  name: rules-prod
spec:
  tls:
  - hosts:
    - beaware.uk-south.containers.mybluemix.net
    secretName: default/beaware
  rules:
  - host: beaware.uk-south.containers.mybluemix.net
    http:
      paths:
