apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jenkins-slave
  name: beaware-jenkins-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      component: beaware-jenkins-slave
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: jenkins-slave
        component: beaware-jenkins-slave
    spec:
      containers:
      - args:
        - 23cf73cba766b68de1f453eba8795ba5614614166572edb0b167a5a84ced4b62
        - beaware-jenkins-slave
        env:
        - name: JENKINS_LOCATION_URL
          value: http://jenkins.beaware.uk-south.containers.mybluemix.net/
        - name: JENKINS_SECRET
          value: 23cf73cba766b68de1f453eba8795ba5614614166572edb0b167a5a84ced4b62
        - name: JENKINS_JNLP_URL
          value: http://beaware-jenkins.default.svc.cluster.local:8080/computer/beaware-jenkins-slave/slave-agent.jnlp
        - name: JENKINS_TUNNEL
          value: beaware-jenkins.default.svc.cluster.local:50000
        - name: JENKINS_NAME
          value: beaware-jenkins-slave
        - name: JENKINS_URL
          value: http://beaware-jenkins.default.svc.cluster.local:8080
        - name: HOME
          value: /home/jenkins
        - name: DOCKER_HOST
          value: docker-engine
        image: registry.eu-gb.bluemix.net/beaware/jenkins-slave
        imagePullPolicy: Always
        name: jnlp
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
          requests:
            cpu: "2"
            memory: 8Gi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        tty: true
        volumeMounts:
        - mountPath: /home/jenkins
          name: workspace-volume
        workingDir: /home/jenkins
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: bluemix-default-secret
      restartPolicy: Always
      securityContext: {}
      serviceAccount: jenkins-slave-sa
      serviceAccountName: jenkins-slave-sa
      volumes:
      - name: workspace-volume
        persistentVolumeClaim:
          claimName: jenkins-slave-data
