apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins-slave
  name: beaware-jenkins-slave
  namespace: build
spec:
  replicas: 1
  selector:
    matchLabels:
      component: beaware-jenkins-slave
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: jenkins-slave
        component: beaware-jenkins-slave
    spec:
      containers:
      - args:
        env:
        - name: JENKINS_LOCATION_URL
          value: http://beaware-1.eu-de.containers.appdomain.cloud/jenkins
        - name: JENKINS_SECRET
          valueFrom:
            secretKeyRef:
              key: jnlp-token
              name: jnlp-secret
        - name: JENKINS_JNLP_URL
          value: http://beaware-jenkins.default.svc.cluster.local:8080/jenkins/computer/beaware-jenkins-slave/slave-agent.jnlp
        - name: JENKINS_TUNNEL
          value: beaware-jenkins.default.svc.cluster.local:50000
        - name: JENKINS_NAME
          value: beaware-jenkins-slave
        - name: JENKINS_URL
          value: http://beaware-jenkins.default.svc.cluster.local:8080/jenkins
        - name: HOME
          value: /home/jenkins
        - name: DOCKER_HOST
          value: docker-engine
        image: beaware/jenkins-slave
        imagePullPolicy: Always
        name: jnlp
        resources:
          limits:
            cpu: "4"
            memory: 16Gi
          requests:
            cpu: "1"
            memory: 4Gi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        tty: true
        volumeMounts:
        - mountPath: /home/jenkins
          name: workspace-volume
        workingDir: /home/jenkins
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: bluemix-default-secret
      restartPolicy: Always
      securityContext: {}
      serviceAccount: jenkins-slave-sa
      serviceAccountName: jenkins-slave-sa
      volumes:
      - name: workspace-volume
        persistentVolumeClaim:
          claimName: jenkins-slave-data
