kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: prod
  name: pv-snsvr
  labels:
    type: ibmc-file-gold
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
