apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-master
    component: beaware-jenkins-master
    release: "2.60.3"
  name: beaware-jenkins
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: slavelistener
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    component: beaware-jenkins-master

